# SERVER
quarkus.http.port=8081

# DATABASE
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=Novisad7
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/gym_quarkus_db

# HIBERNATE
quarkus.hibernate-orm.schema-management.strategy=drop-and-create

# KEYCLOAK (OIDC)
quarkus.oidc.auth-server-url=http://localhost:8080/realms/gym-app-quarkus
quarkus.oidc.client-id=gym-client
quarkus.oidc.credentials.secret=4zMtwxXGfpLMjECkOtH8xM6p80GzEBcV
quarkus.oidc.application-type=service
quarkus.oidc.roles.role-claim-path=realm_access/roles

# SECURITY
quarkus.http.auth.proactive=true

quarkus.rest-client.ip-api.url=https://api.ipify.org
quarkus.rest-client.timezone-api.url=https://timeapi.io

quarkus.rest-client.currency-api.url=https://api.euroratesapi.dev