quarkus.http.port=8081

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=Novisad7
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/gym_quarkus_db

quarkus.hibernate-orm.database.generation=update